import { ComputedRef } from 'vue';
declare const antdvFormItemPropsList: readonly ["autoLink", "colon", "extra", "hasFeedback", "help", "htmlFor", "label", "labelAlign", "labelCol", "name", "required", "rules", "validateFirst", "validateStatus", "validateTrigger", "wrapperCol", "addonBefore", "addonAfter", "addonWarpStyle"];
declare const pickProFormItemProps: <T extends Record<(typeof antdvFormItemPropsList)[number], any>>(props: ComputedRef<T>) => {
    labelCol: any;
    wrapperCol: any;
    colon: any;
    labelAlign: any;
    rules: any;
    name: any;
    validateTrigger: any;
    required: any;
    addonBefore: any;
    addonAfter: any;
    htmlFor: any;
    label: any;
    help: any;
    extra: any;
    hasFeedback: any;
    autoLink: any;
    validateFirst: any;
    validateStatus: any;
    addonWarpStyle: any;
};
export default pickProFormItemProps;
